### PR TITLE
Bella v1

### PR DESCRIPTION
**Pull request by Bellawei0**
1) Created **DeleteNoteServlet**, **InsertNoteServlet** java classes, and **addNote.jsp** 
2) implemented **Insertion** and **Deletion** functionlity 
3) Manipulated data from database **note_meta** table

### CODE REVIEW

**Comment by zychin2000** [comment]
For the insert function, I wasn't able to run it,
java.sql.SQLException: Field 'principle_id' doesn't have a default value
Did you have that exception too?

**Comment by Bellawei0** [comment]
Update: 
Problem Cause:  principle_id had been dropped because we got rid of a weak entity 

two ways to fix:
1) Added SQL statement in V2_Create_person_table.sql 
ALTER TABLE `project157a`.`note_meta` 
DROP COLUMN `principle_id`;

2) export new SQL file from google drive

**Review by thelearningcode — COMMENTED** [review]
Bella helped me set up my environment and convert to Maven to be compatible w Josh's Intellij! Josh and Bella invested multiple hours in uncovering this hurdle for me... I will be able to take a longer look at the pull request and commits these next two days! Thank you two...

**Comment by zychin2000** [comment]
> Update:
> Problem Cause: principle_id had been dropped because we got rid of a weak entity
> 
> two ways to fix:
> 
> 1. Added SQL statement in V2_Create_person_table.sql
>    ALTER TABLE `project157a`.`note_meta`
>    DROP COLUMN `principle_id`;
> 2. export new SQL file from google drive

Yeah, we can delete the principle_id for all 3 of the notes, if you want to create a migration, create a new migration file called V3_<insert_name>, it's okay to create multiple migrations.

**Pull request closed without merging**
