### PR TITLE
Implemented Note page for displaying notes

### PR DESCRIPTION
**Pull request by Bellawei0**
1) added classes: a) Note Model  b)NoteDAO  c)NoteSerlvert  d)note.jsp  e)addNote.jsp 
2) fixed navigation, index.html - > about -> login -> dashboard -> sidebar 
3) After user login, the user will be able to click left sidebar - > Profile, Learn, Note, LogOut 
4) After click Note,  it will connect to the servlet(URL: http://localhost:8080/CS157AProject/notelist) and database, then it will display Note data from Database (note_meta table)

### CODE REVIEW

**Comment by zychin2000** [comment]
1. I think the features aren't done yet, but if there are any requests which will change the database, such as insert, edit delete, it should in doPost instead of doGet, GET requests are mainly used for displaying data.
2. Do not put the notelist at /notelist, as it won't be protected by the filter, and any user would be able to access it. Unless you want to make that page public, please put it behind /dashboard, so it will be /dashboard/notelist.

**Comment by zychin2000** [comment]
Also, I got a problem when launching the application, 
org.apache.jasper.JasperException: The absolute uri: [http://java.sun.com/jsp/jstl/core] cannot be resolved in either web.xml or the jar files deployed with this application

We'll have to add the jstl core to pom.xml, to declare if any new libraries are used.

**Comment by Bellawei0** [comment]
**Update:** 
1) added dependencies in the Pom.xml file and uploaded the corresponding jar files into WEB-INF/lib 
2) moved note.jsp into jsp folder and changed notelist to  /dashboard/notelist.
3) The feature was **retrieving data from the database and displaying in a note page**. that is why It was using doGET method. I cleared the unnecessary code for readability.

**Comment by zychin2000** [comment]
I have added one more change, which displays everything in an album style instead of table, hopefully it looks nicer on your end. Should be able to merge in.

**Review by zychin2000 — APPROVED** [review]
added a little change, go merge it in!

**Pull request merged**
